/**
 * An error thrown when generating a proof fails.
 */ export class ProvingError extends Error {
    retry;
    static NAME = 'ProvingError';
    /**
   * Creates a new instance
   * @param message - The error message.
   * @param cause - The cause of the error.
   * @param retry - Whether the proof should be retried.
   */ constructor(message, cause, retry = false){
        super(message), this.retry = retry;
        this.name = ProvingError.NAME;
        this.cause = cause;
    }
}
